# Generated by Django 5.0 on 2023-12-20 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('yard_area', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2099)])),
                ('garage', models.BooleanField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_submit', models.BooleanField(default=False, editable=False)),
                ('house_review', models.FloatField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MySite.user')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_tenant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('location', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('landlord', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('neighborhood', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('Transportation', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('rating', models.FloatField(default=0, editable=False)),
                ('comment', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='house_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.userprofile'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.property')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.userprofile')),
            ],
        ),
    ]
