# Generated by Django 5.0 on 2023-12-26 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_city', models.CharField(max_length=30)),
                ('house_address', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('yard_area', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2099)])),
                ('garage', models.BooleanField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_submit', models.BooleanField(default=False)),
                ('house_review', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['is_submit', 'is_available'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('T', 'Tenant'), ('U', 'User')], default='U', max_length=1)),
            ],
            options={
                'verbose_name': 'User',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='MySite_user_first_n_698472_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('location', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('landlord', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('neighborhood', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('Transportation', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('rating', models.FloatField(default=0, editable=False)),
                ('comment', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.users')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='house_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.users'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.property')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.users')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['title'], name='MySite_prop_title_680168_idx'),
        ),
    ]
