# Generated by Django 5.0 on 2023-12-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='-', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='-', max_length=25),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['title'], name='MySite_prop_title_680168_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['first_name', 'last_name'], name='MySite_user_first_n_698472_idx'),
        ),
    ]
