# Generated by Django 5.0 on 2023-12-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_users_first_name_users_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('T', 'Tenant'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
