# Generated by Django 5.0 on 2023-12-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_profileuser_alter_document_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yard_area',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
