# Generated by Django 5.0 on 2023-12-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_review',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
