# Generated by Django 5.0 on 2023-12-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_alter_property_garage_alter_property_house_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MySite.user'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
