# Generated by Django 5.0 on 2023-12-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_document_status_alter_property_house_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['status']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['is_submit', 'is_available']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-25T15:30:45.000000Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='house_address',
            field=models.CharField(max_length=255),
        ),
    ]
