# Generated by Django 5.0 on 2024-01-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_alter_profileuser_user_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='house_address',
            field=models.CharField(max_length=255),
        ),
    ]
