# Generated by Django 5.0 on 2023-12-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_alter_document_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
