# Generated by Django 5.0 on 2024-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0008_rename_time_review_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
