# Generated by Django 5.0.1 on 2024-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0009_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
