# Generated by Django 5.0.1 on 2024-02-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0010_alter_property_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='req',
            field=models.CharField(choices=[('O', 'Owner'), ('T', 'Tenant'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
