# Generated by Django 5.0.1 on 2024-02-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0012_remove_profileuser_req_profileuser_requestrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_landlord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_location',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_neighborhood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_transportation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
