# Generated by Django 5.0.1 on 2024-02-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0013_property_house_landlord_property_house_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='MySite/images'),
        ),
    ]
