# Generated by Django 5.0.1 on 2024-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0017_alter_profileuser_requestrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='requestRole',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
