# Generated by Django 5.0.1 on 2024-02-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0019_alter_property_area_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MySite/image'),
        ),
    ]
